name: Update Edge Branch

on:
  push:
    branches: [main]
    
permissions: 
  contents: write

jobs:
  update-edge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "Felipe bot"
          git config user.email "felipe@x.com"

      - name: Update Edge Branch
        run: |
          git checkout main
          git fetch origin
          git checkout edge
          git pull
          git merge origin/main
          git push origin edge
